version: '2'

services:
  jenkins:
    image: proundmega/auditoria2017-jenkins
    build: ./docker/jenkins
    ports:
      - 8000:8080
    links:
      - sonarqube
    hostname: jenkins
    volumes:
      - ./config/jenkins:/var/jenkins_home:Z
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    image: sonarqube:6.4
    ports:
      - 9000:9000
    hostname: sonarqube

  
