version: '2'

services:
  jenkins:
    image: proundmega/auditoria2017-jenkins
    ports:
      - 8000:8080
    links:
      - gitlab
      - sonarqube
    hostname: jenkins

  gitlab:
    image: proundmega/auditoria2017-gitlab
    ports:
      - "80:80"
      - "10022:22"
    hostname: gitlab

  sonarqube:
    image: sonarqube:6.4
    ports:
      - 9000:9000
    hostname: sonarqube
